import assert from 'node:assert/strict';
import fs from 'node:fs';
import { spawnSync } from 'node:child_process';

const script = fs.readFileSync('scripts/download_youtube_karaoke.sh', 'utf8');
const readme = fs.readFileSync('README.md', 'utf8');
const links = fs.readFileSync('links.txt', 'utf8').trim().split(/\n+/);

const syntax = spawnSync('bash', ['-n', 'scripts/download_youtube_karaoke.sh'], { encoding:'utf8' });
assert.equal(syntax.status, 0, syntax.stderr);
assert.match(script, /command -v "\$1"/);
assert.match(script, /need_cmd yt-dlp/);
assert.match(script, /need_cmd ffmpeg/);
assert.match(script, /mkdir -p "\$MP4_DIR" "\$MP3_DIR" "\$LOG_DIR"/);
assert.match(script, /archive-mp4\.txt/);
assert.match(script, /archive-mp3\.txt/);
assert.doesNotMatch(script, /mapfile/);
assert.match(script, /while IFS= read -r line/);
assert.match(script, /--continue/);
assert.match(script, /--no-abort-on-error/);
assert.match(script, /--ignore-errors/);
assert.match(script, /--restrict-filenames/);
assert.match(script, /--windows-filenames/);
assert.match(script, /%\(title\)\.180B \[%\(id\)s\]/);
assert.match(script, /bv\*\[ext=mp4\]\+ba\[ext=m4a\]/);
assert.match(script, /--merge-output-format mp4/);
assert.match(script, /--audio-format mp3/);
assert.match(script, /--audio-quality 0/);
assert.match(script, /--embed-metadata/);
assert.match(script, /--embed-thumbnail/);
assert.match(script, /MP4 SUCCESS/);
assert.match(script, /MP4 FAILURE/);
assert.match(script, /MP3 SUCCESS/);
assert.match(script, /MP3 FAILURE/);
assert.equal(links.length, 31);
assert.ok(links.every(url => /^https:\/\/www\.youtube\.com\/watch\?v=/.test(url)));
assert.match(readme, /brew install yt-dlp ffmpeg/);
assert.match(readme, /python3 -m pip install -U "yt-dlp\[default\]"/);
assert.match(readme, /Exact commands run per URL/);
console.log('PASS downloader static contract');
