import fs from 'node:fs';
const checks = [];
const webrtc = fs.readFileSync('src/webrtc.ts','utf8');
checks.push(['public STUN configured', webrtc.includes('stun:stun.l.google.com:19302')]);
checks.push(['manual waits complete ICE', webrtc.includes('waitForIceComplete') && webrtc.includes('iceGatheringState') && webrtc.includes('complete')]);
checks.push(['no TURN required', !webrtc.toLowerCase().includes('turn:')]);
const state = fs.readFileSync('src/state.ts','utf8');
checks.push(['5 player cap', state.includes('MAX_PLAYERS = 5') && state.includes('maxPlayers: MAX_PLAYERS')]);
checks.push(['5 singer cap', state.includes('MAX_SINGERS = 5')]);
checks.push(['queue cap 20', state.includes('MAX_QUEUE_ITEMS = 20')]);
checks.push(['crypto random UUID', state.includes('crypto.randomUUID')]);
const app = fs.readFileSync('src/app.ts','utf8');
checks.push(['phone offer creation has WebRTC/local HTTP guidance', webrtc.includes('assertWebRtcSupported') && webrtc.includes('local HTTP hostnames may block offer creation') && app.includes('Create player offer for host') && app.includes('GitHub Pages HTTPS URL')]);
checks.push(['host registers ROOM_HELLO players', app.includes('msg.type===RPC.ROOM_HELLO') && app.includes('registerRemotePlayer') && app.includes('addPlayer(room')]);
checks.push(['host sends queue and singer Cast updates', app.includes('CAST_UPDATE_QUEUE_PREVIEW') && app.includes('CAST_SET_SINGERS')]);
checks.push(['host exposes pause seek and remote mute controls', app.includes('id="castPause"') && app.includes('id="castSeek"') && app.includes('class="mutePlayer"') && app.includes('type:RPC.MIC_MUTED')]);
checks.push(['cast current song is one-click connect and load', app.includes('Cast current song to TV') && app.includes('Connecting to Chromecast') && app.includes('await cast.init()') && app.includes('await loadCurrentSongOnTv()')]);
checks.push(['cast load autoplays TV media', fs.readFileSync('src/cast.ts','utf8').includes('request.autoplay = true') && fs.readFileSync('src/cast.ts','utf8').includes('await this.play()') && fs.readFileSync('src/cast.ts','utf8').includes('media.play().catch')]);
checks.push(['cast media origin override for Chromecast LAN access', app.includes('id="castOrigin"') && app.includes('carryokie.castOrigin') && fs.readFileSync('src/cast.ts','utf8').includes('rewriteCastUrlForReceiver')]);
checks.push(['phone lyric video syncs from Cast samples', app.includes('syncPhoneVideo') && app.includes('deriveTvMediaPositionMs(room.playbackState') && app.includes('phoneVideo') && app.includes('muted')]);
checks.push(['host exposes manual answer flow', app.includes('id="offer"') && app.includes('Paste player offer/link/chunks') && app.includes('id="scanOfferQr"') && app.includes('id="answerOffer"') && app.includes('acceptManualOffer') && app.includes('Host answer')]);
checks.push(['player exposes manual answer import', app.includes('id="answer"') && app.includes('Paste host answer/link/chunks') && app.includes('id="scanAnswerQr"') && app.includes('id="importAnswer"') && app.includes('acceptManualAnswer')]);
checks.push(['player exposes singer slot request', app.includes('id="requestSinger"') && app.includes('type:RPC.SINGER_JOIN_REQUEST')]);
checks.push(['mic publishing requires singer assignment in UI', app.includes('Mic blocked: ask the host to assign you as a singer') && app.includes('isSingerForCurrentSong')]);
checks.push(['host can start next queued song', app.includes('startQueueItem') && app.includes('id="startNext"') && app.includes("item.status = 'active'") && app.includes('currentQueueItemId')]);
checks.push(['queue can recover and start rejected items', app.includes('class="acceptItem"') && app.includes('class="startItem"') && app.includes("['requested','rejected']") && app.includes("q.status==='rejected'")]);
checks.push(['queue start loads current song on connected Cast', app.includes('loadCurrentSongOnTv') && app.includes('castController?.state?.().connected') && app.includes('Loaded ${song.title || song.songId} on TV')]);
checks.push(['host handles PLAYER_LEFT on disconnect', app.includes('handlePlayerLeft') && app.includes('RPC.PLAYER_LEFT')]);
checks.push(['participant locks room on host disconnect', app.includes('handlePeerClosed') && app.includes('lockHostLost(room)') && app.includes('isHostEdge')]);
checks.push(['host tracks MIC_ENABLED from players', app.includes('msg.type===RPC.MIC_ENABLED') && app.includes('micState')]);
checks.push(['host has reject/remove queue controls', app.includes('rejectQueue') && app.includes('removeQueueItem') && app.includes('class="rejectItem"')]);
checks.push(['player has reconnect UI', app.includes('reconnectPair') && app.includes('forgetRoom')]);
checks.push(['debug page exposes connection diagnostics', app.includes('Connection diagnostics') && app.includes('dataChannelPeerIds') && app.includes('clockOffsetMs') && app.includes('micPermission')]);
const cast = fs.readFileSync('src/cast.ts','utf8');
checks.push(['Cast sync uses media status', cast.includes('currentTime') && cast.includes('RemotePlayerController')]);
checks.push(['protected catalog is primary media source', app.includes('loadProtectedCatalog') && fs.existsSync('public/protected/catalog.json')]);
const protectedMediaCode = fs.readFileSync('src/protectedMedia.ts','utf8');
checks.push(['local phone crypto fallback for protected media', protectedMediaCode.includes('hasWebCryptoAes') && protectedMediaCode.includes('song.defaultCastMediaUrl') && protectedMediaCode.includes('Use HTTPS/GitHub Pages')]);
checks.push(['Default Media Receiver skips custom namespace sends', cast.includes('DEFAULT_MEDIA_RECEIVER_APP_ID') && cast.includes('usesDefaultMediaReceiver')]);
checks.push(['receiver renders join QR lyrics and singers', cast.includes("import { qrSvg }") && cast.includes('id="joinQr"') && cast.includes('CAST_SET_SINGERS') && cast.includes('CAST_SYNC_PLAYBACK_STATE') && cast.includes('loadLyrics') && cast.includes('timeupdate')]);
const receiver = fs.readFileSync('receiver/index.html','utf8');
checks.push(['no WebRTC in receiver page', !receiver.includes('RTCPeerConnection') && !receiver.includes('getUserMedia')]);
checks.push(['receiver loads CAF framework', receiver.includes('cast_receiver_framework.js') && cast.includes('addCustomMessageListener')]);
const audio = fs.readFileSync('src/audio.ts','utf8');
checks.push(['AEC warning copy', audio.includes('TV backing track')]);
checks.push(['push-to-sing support', audio.includes('pushToSing')]);
checks.push(['noise gate implemented', audio.includes('ScriptProcessor') && audio.includes('gateThreshold') && audio.includes('setGateEnabled')]);
const signaling = fs.readFileSync('src/signaling.ts','utf8');
checks.push(['camera QR import exists', signaling.includes('BarcodeDetector') && app.includes('scanQrInto')]);
checks.push(['single visible QR constraint', signaling.includes('data-single-qr') && !signaling.includes('map((chunk, i) => `<figure>')]);
checks.push(['ManualQrSignalingAdapter exists', signaling.includes('class ManualQrSignalingAdapter')]);
checks.push(['PeerRelaySignalingAdapter exists', signaling.includes('class PeerRelaySignalingAdapter')]);
const protectedCatalog = JSON.parse(fs.readFileSync('public/protected/catalog.json','utf8'));
checks.push(['protected catalog has songs', protectedCatalog.songs?.length > 0]);
checks.push(['public songs folder removed', !fs.existsSync('public/songs')]);
for (const page of ['host', 'player', 'receiver', 'debug']) {
  const sourceHtml = fs.readFileSync(`${page}/index.html`, 'utf8');
  checks.push([`${page} source redirects GitHub Pages traffic to dist`, sourceHtml.includes("host.endsWith('github.io')") && sourceHtml.includes("parts.includes('dist')") && sourceHtml.includes("'dist',page,''])")]);
}
const distHtml = ['dist/host/index.html','dist/player/index.html','dist/receiver/index.html','dist/debug/index.html'].map(f=>fs.existsSync(f)?fs.readFileSync(f,'utf8'):'').join('\n');
checks.push(['dist never serves TypeScript module scripts', !distHtml.includes('src/main.ts') && !distHtml.includes('.ts"')]);
let failed = 0;
for (const [name, ok] of checks) { console.log((ok ? 'PASS ' : 'FAIL ') + name); if (!ok) failed++; }
if (failed) process.exit(1);
console.log('All static checks passed');
