import fs from 'node:fs';
const checks = [];
const webrtc = fs.readFileSync('src/webrtc.ts','utf8');
checks.push(['public STUN configured', webrtc.includes('stun:stun.l.google.com:19302')]);
checks.push(['manual waits complete ICE', webrtc.includes('waitForIceComplete') && webrtc.includes('iceGatheringState') && webrtc.includes('complete')]);
checks.push(['no TURN required', !webrtc.toLowerCase().includes('turn:')]);
const state = fs.readFileSync('src/state.ts','utf8');
checks.push(['5 player cap', state.includes('MAX_PLAYERS = 5') && state.includes('maxPlayers: MAX_PLAYERS')]);
checks.push(['5 singer cap', state.includes('MAX_SINGERS = 5')]);
checks.push(['queue cap 20', state.includes('MAX_QUEUE_ITEMS = 20')]);
checks.push(['crypto random UUID', state.includes('crypto.randomUUID')]);
const app = fs.readFileSync('src/app.ts','utf8');
checks.push(['host registers ROOM_HELLO players', app.includes('msg.type===RPC.ROOM_HELLO') && app.includes('registerRemotePlayer') && app.includes('addPlayer(room')]);
checks.push(['host sends queue and singer Cast updates', app.includes('CAST_UPDATE_QUEUE_PREVIEW') && app.includes('CAST_SET_SINGERS')]);
checks.push(['host exposes pause seek and remote mute controls', app.includes('id="castPause"') && app.includes('id="castSeek"') && app.includes('class="mutePlayer"') && app.includes('type:RPC.MIC_MUTED')]);
checks.push(['player exposes singer slot request', app.includes('id="requestSinger"') && app.includes('type:RPC.SINGER_JOIN_REQUEST')]);
checks.push(['host can start next queued song', app.includes('startQueueItem') && app.includes('id="startNext"') && app.includes("item.status = 'active'") && app.includes('currentQueueItemId')]);
checks.push(['host handles PLAYER_LEFT on disconnect', app.includes('handlePlayerLeft') && app.includes('RPC.PLAYER_LEFT')]);
checks.push(['host tracks MIC_ENABLED from players', app.includes('msg.type===RPC.MIC_ENABLED') && app.includes('micState')]);
checks.push(['host has reject/remove queue controls', app.includes('rejectQueue') && app.includes('removeQueueItem') && app.includes('class="rejectItem"')]);
checks.push(['player has reconnect UI', app.includes('reconnectPair') && app.includes('forgetRoom')]);
const cast = fs.readFileSync('src/cast.ts','utf8');
checks.push(['Cast sync uses media status', cast.includes('currentTime') && cast.includes('RemotePlayerController')]);
checks.push(['protected catalog is primary media source', app.includes('loadProtectedCatalog') && fs.existsSync('public/protected/catalog.json')]);
checks.push(['Default Media Receiver skips custom namespace sends', cast.includes('DEFAULT_MEDIA_RECEIVER_APP_ID') && cast.includes('usesDefaultMediaReceiver')]);
checks.push(['receiver renders join QR lyrics and singers', cast.includes("import { qrSvg }") && cast.includes('id="joinQr"') && cast.includes('CAST_SET_SINGERS') && cast.includes('CAST_SYNC_PLAYBACK_STATE') && cast.includes('loadLyrics') && cast.includes('timeupdate')]);
const receiver = fs.readFileSync('receiver/index.html','utf8');
checks.push(['no WebRTC in receiver page', !receiver.includes('RTCPeerConnection') && !receiver.includes('getUserMedia')]);
checks.push(['receiver loads CAF framework', receiver.includes('cast_receiver_framework.js') && cast.includes('addCustomMessageListener')]);
const audio = fs.readFileSync('src/audio.ts','utf8');
checks.push(['AEC warning copy', audio.includes('TV backing track')]);
checks.push(['push-to-sing support', audio.includes('pushToSing')]);
checks.push(['noise gate implemented', audio.includes('ScriptProcessor') && audio.includes('gateThreshold') && audio.includes('setGateEnabled')]);
const signaling = fs.readFileSync('src/signaling.ts','utf8');
checks.push(['ManualQrSignalingAdapter exists', signaling.includes('class ManualQrSignalingAdapter')]);
checks.push(['PeerRelaySignalingAdapter exists', signaling.includes('class PeerRelaySignalingAdapter')]);
const protectedCatalog = JSON.parse(fs.readFileSync('public/protected/catalog.json','utf8'));
checks.push(['protected catalog has songs', protectedCatalog.songs?.length > 0]);
checks.push(['public songs folder removed', !fs.existsSync('public/songs')]);
let failed = 0;
for (const [name, ok] of checks) { console.log((ok ? 'PASS ' : 'FAIL ') + name); if (!ok) failed++; }
if (failed) process.exit(1);
console.log('All static checks passed');
